SRCS=\
	apex.cpp \
	code.cpp \
	cpu.cpp \
	data.cpp \
	iq.cpp \
	main.cpp \
	register.cpp \
	rob.cpp \
	simulate.cpp \
	stage.cpp
OBJS=$(SRCS:.cpp=.o)

all: $(OBJS)

.PHONY:clean
clean:
	$(RM) $(OBJS)